# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
linter:
   rules:
      #     - hash_and_equals
      - close_sinks
      - empty_statements
      - invariant_booleans
      - iterable_contains_unrelated_type
      - list_remove_unrelated_type

#   https://www.dartlang.org/guides/language/analysis-options
analyzer:
   exclude: [build/**]
   errors:
      uri_has_not_been_generated: ignore
      # Angular plugin support is in beta. You're welcome to try it and report
      # issues: https://github.com/dart-lang/angular_analyzer_plugin/issues
      # plugins:
      # - angular